# built with Flutter 3.38.5 (Mac Apple M1), Dart SDK 3.10.4, CocoaPods 1.16.2, Xcode 26.2
name: tommyplayer
description: Tommy Player for iOS, Android and MacOS (Windows/Linux are not supported)
version: 1.8.0+24

environment:
  sdk: '>=3.10.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  just_audio: 0.10.5                    # audio player (Windows and Linux are not supported)
  just_audio_background: 0.0.1-beta.17  # background playback support
  http: 1.6.0                           # http support
  html: 0.15.6                          # html support
  scoped_model: 2.0.0                   # simple state management
  uuid: 4.5.2                           # generate unique ID for a song for background audio service
  shared_preferences: 2.5.4             # key-value local storage
  package_info_plus: 9.0.0              # build info
  share_plus: 12.0.1                    # share-dialog
  path_provider: 2.1.5                  # getTemporaryDirectory()
  cupertino_icons: 1.0.8                # extra icons
  line_icons: 2.0.3                     # extra icons

flutter:
  uses-material-design: true            # Material Icons font

dev_dependencies:
  flutter_launcher_icons: 0.14.4        # Icons generator, run: "dart run flutter_launcher_icons"

flutter_launcher_icons:
  ios: true
  image_path: "installer/mac/appicon.png"
  macos:
    generate: true
    image_path: "installer/mac/appicon.png"
