# built with Flutter 3.7.12, CocoaPods 1.11.3
name: tommyplayer
description: Tommy's Player

version: 23.8.25+10

environment:
  sdk: ">=2.19.6 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  just_audio: 0.9.34                    # audio player
  just_audio_background: 0.0.1-beta.10  # background playback support
  http: 0.13.6                          # http support
  html: 0.15.3                          # html support
  uuid: 3.0.7                           # uuid support
  scoped_model: 2.0.0                   # simple state management
  cupertino_icons: 1.0.5                # extra icons

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: 2.0.1                  # linter from `analysis_options.yaml`

flutter:
  uses-material-design: true            # Material Icons font
