# built with Flutter 3.19.4, CocoaPods 1.16.2
name: tommyplayer
description: Tommy Player

version: 24.3.26+15

environment:
  sdk: '>=3.2.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  just_audio: 0.9.36                    # audio player (0.9.34 is stable, 0.9.36 is possibly unstable)
  just_audio_background: 0.0.1-beta.10  # background playback support (beta.10 is stable, beta.11 is possibly unstable)
  http: 1.2.0                           # http support (1.2.1 is incompatible with sdk 3.2.6)
  html: 0.15.4                          # html support
  uuid: 4.3.3                           # uuid support
  scoped_model: 2.0.0                   # simple state management
  cupertino_icons: 1.0.6                # extra icons
  shared_preferences: 2.2.2             # key-value storage
  package_info_plus: 5.0.1              # build info
  f_logs: 2.0.1                         # logger

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: 3.0.1                  # linter from `analysis_options.yaml`

flutter:
  uses-material-design: true            # Material Icons font
