# built with Flutter 2.8.x
name: tommyplayer
description: Tommy's Player

version: 1.0.0+1

environment:
  sdk: ">=2.15.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  just_audio: ^0.9.29                   # audio player
  just_audio_background: ^0.0.1-beta.7  # background playback support
  http: ^0.13.5                         # http support
  html: ^0.15.0                         # html support
  uuid: ^3.0.6                          # uuid support
  scoped_model: 2.0.0-nullsafety.0      # simple state management
  cupertino_icons: ^1.0.5               # extra icons

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0                 # linter from `analysis_options.yaml`

flutter:
  uses-material-design: true            # Material Icons font
